name: e_shoes
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0 # Pastikan versi SDK ini sesuai dengan instalasi Flutter Anda

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5 # Dipertahankan dari versi HEAD
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/banner.png
    - assets/images/product1.png
    - assets/images/product2.png
    - assets/images/product3.png
    - assets/images/product4.png
    - assets/images/product5.png
    - assets/images/popular1.png
    - assets/images/popular2.png
    - assets/images/popular3.png
    - assets/images/popular4.png
    - assets/images/popular5.png
    - assets/images/banner2.png
    - assets/images/sepatu_atas.png
    - assets/images/sepatu_side.png
    - assets/images/sepatu_bottom.png
    - assets/images/sepatu_back.png
    - assets/images/profile.png
    - assets/images/toko.png
    - assets/images/eiger_logo_full.png # Ditambahkan dari versi lainnya
    - assets/images/eiger_logo_white.png # Ditambahkan dari versi lainnya
    - assets/images/bryce_lowcut.png # Ditambahkan dari versi lainnya

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700