// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA49ot-LAvpRLsEIsYSkmOwjx_nXyoeNmI',
    appId: '1:875874761809:web:442c443ec7b056379a8c70',
    messagingSenderId: '875874761809',
    projectId: 'toko-sepatu-eiger-5ab03',
    authDomain: 'toko-sepatu-eiger-5ab03.firebaseapp.com',
    storageBucket: 'toko-sepatu-eiger-5ab03.firebasestorage.app',
    measurementId: 'G-13XW3MW5V5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1Q6GwbEYjUV7FlTVQR372ADNJkAUSfko',
    appId: '1:875874761809:android:6aff670eebefd2439a8c70',
    messagingSenderId: '875874761809',
    projectId: 'toko-sepatu-eiger-5ab03',
    storageBucket: 'toko-sepatu-eiger-5ab03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbe8DkRmVOzxg8iYvThM8-Bece_eyphm4',
    appId: '1:875874761809:ios:974bd33c8065672c9a8c70',
    messagingSenderId: '875874761809',
    projectId: 'toko-sepatu-eiger-5ab03',
    storageBucket: 'toko-sepatu-eiger-5ab03.firebasestorage.app',
    iosBundleId: 'com.example.eShoes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbe8DkRmVOzxg8iYvThM8-Bece_eyphm4',
    appId: '1:875874761809:ios:974bd33c8065672c9a8c70',
    messagingSenderId: '875874761809',
    projectId: 'toko-sepatu-eiger-5ab03',
    storageBucket: 'toko-sepatu-eiger-5ab03.firebasestorage.app',
    iosBundleId: 'com.example.eShoes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA49ot-LAvpRLsEIsYSkmOwjx_nXyoeNmI',
    appId: '1:875874761809:web:0bde7392fc5eb79d9a8c70',
    messagingSenderId: '875874761809',
    projectId: 'toko-sepatu-eiger-5ab03',
    authDomain: 'toko-sepatu-eiger-5ab03.firebaseapp.com',
    storageBucket: 'toko-sepatu-eiger-5ab03.firebasestorage.app',
    measurementId: 'G-W62MCS4FXY',
  );
}
