// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6NriQjN-j8iHdoHhdNJ8SJ4Ca4H1ffN8',
    appId: '1:564607430418:web:ea29fb03676388c6658dcb',
    messagingSenderId: '564607430418',
    projectId: 'e-shoes-f6b2e',
    authDomain: 'e-shoes-f6b2e.firebaseapp.com',
    storageBucket: 'e-shoes-f6b2e.firebasestorage.app',
    measurementId: 'G-JS1Z83091B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC60lpsDcgiY8ffoqIKE90eKbCMsDIDoM',
    appId: '1:564607430418:android:0651b97e7f028b90658dcb',
    messagingSenderId: '564607430418',
    projectId: 'e-shoes-f6b2e',
    storageBucket: 'e-shoes-f6b2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa9bywAFrm4qfYIl2YGfll3jMwBaP80Yk',
    appId: '1:564607430418:ios:e1f0f45419ad76da658dcb',
    messagingSenderId: '564607430418',
    projectId: 'e-shoes-f6b2e',
    storageBucket: 'e-shoes-f6b2e.firebasestorage.app',
    iosBundleId: 'com.example.eShoes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa9bywAFrm4qfYIl2YGfll3jMwBaP80Yk',
    appId: '1:564607430418:ios:e1f0f45419ad76da658dcb',
    messagingSenderId: '564607430418',
    projectId: 'e-shoes-f6b2e',
    storageBucket: 'e-shoes-f6b2e.firebasestorage.app',
    iosBundleId: 'com.example.eShoes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6NriQjN-j8iHdoHhdNJ8SJ4Ca4H1ffN8',
    appId: '1:564607430418:web:ab01bfffb34f3f90658dcb',
    messagingSenderId: '564607430418',
    projectId: 'e-shoes-f6b2e',
    authDomain: 'e-shoes-f6b2e.firebaseapp.com',
    storageBucket: 'e-shoes-f6b2e.firebasestorage.app',
    measurementId: 'G-4V1RPPHRM7',
  );

}